"""LLM caller — dùng OpenAI thật nếu có OPENAI_API_KEY, fallback về mock."""
import os
import random
import time
import logging

logger = logging.getLogger(__name__)

# ── Mock responses (fallback khi không có key) ────────────────────────────
MOCK_RESPONSES = {
    "default": [
        "This is a mock AI response. In production, this would come from a real LLM provider.",
        "The chatbot received your question and is running correctly.",
        "Cloud deployment is working; this response was generated by the mock LLM.",
    ],
    "docker": [
        "Docker packages the app and its dependencies so it can run consistently across environments."
    ],
    "deploy": [
        "Deployment moves code from a local machine to a server or cloud platform where users can access it."
    ],
    "health": [
        "The chatbot is healthy and ready to serve traffic."
    ],
    "hello": [
        "Hello! I'm your AI chatbot running on Railway. How can I help you today?"
    ],
}


def _mock_ask(question: str, delay: float = 0.1) -> str:
    time.sleep(delay + random.uniform(0, 0.05))
    q = question.lower()
    for keyword, responses in MOCK_RESPONSES.items():
        if keyword in q:
            return random.choice(responses)
    return random.choice(MOCK_RESPONSES["default"])


# ── OpenAI real LLM ───────────────────────────────────────────────────────
_openai_client = None


def _get_openai_client():
    global _openai_client
    if _openai_client is not None:
        return _openai_client
    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not api_key:
        return None
    try:
        from openai import OpenAI
        _openai_client = OpenAI(api_key=api_key)
        logger.info("OpenAI client initialized (model=%s)", os.getenv("LLM_MODEL", "gpt-4o-mini"))
        return _openai_client
    except ImportError:
        logger.warning("openai package not installed; falling back to mock LLM")
        return None
    except Exception as exc:
        logger.warning("Failed to init OpenAI client: %s; using mock LLM", exc)
        return None


def _openai_ask(question: str) -> str:
    client = _get_openai_client()
    model = os.getenv("LLM_MODEL", "gpt-4o-mini")
    resp = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": question}],
        max_tokens=512,
        temperature=0.7,
    )
    return resp.choices[0].message.content.strip()


# ── Public API ────────────────────────────────────────────────────────────
def ask(question: str, delay: float = 0.1) -> str:
    """Call real OpenAI if OPENAI_API_KEY is set, otherwise return mock response."""
    client = _get_openai_client()
    if client is not None:
        try:
            return _openai_ask(question)
        except Exception as exc:
            logger.error("OpenAI call failed (%s); falling back to mock", exc)
    return _mock_ask(question, delay)
